import { Component, AfterViewInit, Inject, PLATFORM_ID, ViewChild, ElementRef } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { Title, Meta } from '@angular/platform-browser';
import { LucideAngularModule } from 'lucide-angular';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

@Component({
  selector: 'app-services',
  standalone: true,
  imports: [
    CommonModule, 
    LucideAngularModule
  ],
  templateUrl: './services.component.html',
  styleUrls: ['./services.component.css']
})
export class ServicesComponent implements AfterViewInit {
  isBrowser: boolean;

  services = [
    {
      title: 'Academic Plagiarism Detection',
      desc: 'Specialized scanning for essays, theses, and dissertations with institutional database cross-referencing.',
      icon: 'graduation-cap'
    },
    {
      title: 'Website Content Checking',
      desc: 'Protect your SEO and brand by ensuring your web content is unique and not scraped from elsewhere.',
      icon: 'globe'
    },
    {
      title: 'AI Generated Content Detection',
      desc: 'Advanced neural networks to identify text generated by GPT-4, Claude, and other LLMs.',
      icon: 'cpu'
    }
  ];

  @ViewChild('heroTitle') heroTitleRef!: ElementRef;

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    private titleService: Title,
    private metaService: Meta
  ) {
    this.isBrowser = isPlatformBrowser(this.platformId);
    // Sitelink-optimized meta for Pricing sub-result
    this.titleService.setTitle('Pricing & Plans — Free AI Plagiarism Checker Plans | PlagiarismGuard');
    this.metaService.updateTag({
      name: 'description',
      content: 'Explore PlagiarismGuard\'s free and premium plans. Get unlimited plagiarism and AI content detection for students, researchers, and professional content teams.'
    });
    if (this.isBrowser) {
      gsap.registerPlugin(ScrollTrigger);
    }
  }

  ngAfterViewInit() {
    if (this.isBrowser) {
      this.initHeroAnimations();
      this.initPricingAnimations();
      this.initCommonAnimations();
    }
  }

  private initHeroAnimations() {
    gsap.from(this.heroTitleRef.nativeElement, {
      y: 30,
      opacity: 0,
      duration: 1.2,
      ease: 'power4.out',
      clearProps: 'all'
    });

    gsap.from('.hero-desc', {
      opacity: 0,
      y: 20,
      duration: 1,
      delay: 0.8,
      ease: 'power3.out'
    });
  }

  private initPricingAnimations() {
    // Pricing cards entrance
    gsap.from(".pricing-card", {
      y: 60,
      opacity: 0,
      stagger: 0.15,
      duration: 1,
      ease: 'power3.out',
      scrollTrigger: {
        trigger: ".pricing-grid",
        start: "top 85%"
      },
      clearProps: 'all'
    });

    // Pro card highlight pulse
    gsap.to(".pro-card", {
      boxShadow: "0 0 50px rgba(0,194,255,0.25)",
      repeat: -1,
      yoyo: true,
      duration: 2,
      ease: 'sine.inOut'
    });
  }

  private initCommonAnimations() {
    gsap.from('.service-card-alt', {
      scrollTrigger: {
        trigger: '.services-grid-wrapper',
        start: 'top 85%'
      },
      scale: 0.9,
      opacity: 0,
      stagger: 0.1,
      duration: 0.8,
      ease: 'back.out(1.4)',
      clearProps: 'all'
    });

    gsap.from('.enterprise-cta-banner', {
      scrollTrigger: {
        trigger: '.enterprise-cta-banner',
        start: 'top 90%'
      },
      y: 40,
      opacity: 0,
      duration: 1.2,
      ease: 'power3.out'
    });
  }
}
